# Generated by Django 4.1.7 on 2023-03-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_products_tag_alter_products_product_name_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
